### ISSUE TITLE
extended f/t command not working with y/d/c commands

### ISSUE THREAD

**Issue by cellsummer** [TheSafdarAwan/find-extender.nvim#2]
It looks like the plugin won't work in commands such as `df`, `cf` and `yf`. Is there a config option I will need to turn on?

**Comment by TheSafdarAwan** [comment]
> It looks like the plugin won't work in commands such as `df`, `cf` and `yf`. Is there a config option I will need to turn on?

y/d/c commands has been added and the README has also been update see the configuration section.
